---
- name: Minecraft
  hosts: localhost
  user: root
  vars:
    server_version: 1.13
  tasks:
    - name: Install jdk, screen, & awscli
      apt: name={{item}} state=installed update_cache=true
      with_items:
        - default-jdk
        - screen
        - awscli

    - name: Create minecraft dir
      file: state=directory path=/root/minecraft

    - name: Download minecraft 1.13 pre2
      command: wget -O minecraft_server.jar https://launcher.mojang.com/mc/game/1.13.1-pre2/server/c2a4bcf3e244c46f13c39e31e7ef6030564fb6c2/server.jar chdir=/root/minecraft creates=/root/minecraft/minecraft_server.jar

    - name: Prompt Terms & Conditions
      command: screen -S minecraft -d -m java -Xmx512M -Xms512M -jar /root/minecraft/minecraft_server.jar

    - pause:
        seconds: 30

    - name: Agree to Terms & Conditions
      command: sed -i 's/false/true/g' ~/eula.txt

    - name: Run Minecraft
      command: screen -S minecraft -d -m java -Xmx512M -Xms512M -jar /root/minecraft/minecraft_server.jar