---
- name: Minecraft
  hosts: localhost
  user: root
  tasks:
    - name: Install jdk, screen, awscli0, & inotify-tools
      apt: name={{item}} state=installed update_cache=true
      with_items:
        - default-jdk
        - screen
        - awscli
        - inotify-tools

    - name: Create minecraft dir
      file: state=directory path=/root/minecraft

    - name: Download minecraft 1.13.1
      command: wget -O minecraft_server.jar https://launcher.mojang.com/v1/objects/1f8673dee28ff3a1714e17780f6b91d5372fe440/server.jar chdir=/root/minecraft creates=/root/minecraft/minecraft_server.jar

    - name: Prompt Terms & Conditions
      command: screen -S minecraft -d -m java -Xmx512M -Xms512M -jar /root/minecraft/minecraft_server.jar

    - pause:
        seconds: 20

    - name: Agree to Terms & Conditions
      command: sed -i 's/false/true/g' ~/eula.txt

    - name: Run Minecraft
      command: screen -S minecraft -d -m java -Xmx8192M -Xms8192M -jar /root/minecraft/minecraft_server.jar

    - pause:
        seconds: 20
    
    - name: Listen to Logs
      command: inotifywait -qm --event modify --format '%w' logs/latest.log | ./scripts/notify_whos_online.sh