---
- name: Minecraft
  hosts: localhost
  user: root
  tasks:
    - name: Install jdk, screen, & awscli
      apt: name={{item}} state=installed update_cache=true
      with_items:
        - default-jdk
        - screen
        - awscli

    - name: Create minecraft dir
      file: state=directory path=/root/minecraft

    - name: Download minecraft 1.13.2
      command: wget -O minecraft_server.jar https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar chdir=/root/minecraft creates=/root/minecraft/minecraft_server.jar

    - name: Prompt Terms & Conditions
      command: screen -S minecraft -d -m java -Xmx8192M -Xms8192M -jar /root/minecraft/minecraft_server.jar

    - pause:
        seconds: 30

    - name: Agree to Terms & Conditions
      command: sed -i 's/false/true/g' ~/eula.txt

    - name: Run Minecraft
      command: screen -S minecraft -d -m java -Xmx8192M -Xms8192M -jar /root/minecraft/minecraft_server.jar